export const across = {
  1: { text: 'Channel for "Mad Money"', answer: "cnbc" },
  5: { text: "Hoarse vocal quality", answer: "rasp" },
  9: { text: "Eponymous prize awarded by the Mystery Writers of America", answer: "edgar" },
  14: { text: "Lyft competitor", answer: "uber" },
  15: { text: "Ireland, to the Irish", answer: "eire" },
  16: { text: "Frontline health care professional", answer: "nurse" },
  17: { text: "Computer input", answer: "data" },
  18: { text: "*Colorful cereal with the mascot Toucan Sam", answer: "frootloops" },
  20: { text: "Omani currency", answer: "rial" },
  22: { text: "King: Fr.", answer: "roi" },
  23: { text: "Successor of Nintendo's GameCube", answer: "wii" },
  24: { text: '*"Uh-oh, ___!" (classic line in commercials)', answer: "spaghettios" },
  28: { text: "Catering container", answer: "urn" },
  29: { text: "Contents of a farmyard stack", answer: "hay" },
  30: { text: 'Sound represented by an upside-down "e"', answer: "schwa" },
  31: { text: "Capture on cassette", answer: "tape" },
  33: { text: 'Star of the Disney animated short "Once Upon a Snowman"', answer: "olaf" },
  35: { text: "___-state area (N.Y., N.J. and Conn., e.g.)", answer: "tri" },
  36: { text: "Coop resident", answer: "hen" },
  37: { text: "Nutritionist's recommendation ... or what the answers to the starred clues make up, to an overly literal person", answer: "wellroundeddiet" },
  43: { text: "Big part of a basset hound", answer: "ear" },
  44: { text: "Korean automaker", answer: "kia" },
  45: { text: "Memo starter", answer: "inre" },
  46: { text: "Radio button that's handy on a road trip", answer: "scan" },
  48: { text: "Food strainer", answer: "sieve" },
  50: { text: "24 horas", answer: "dia" },
  51: { text: "New ___ smell", answer: "car" },
  52: { text: "*Bulk purchase of Gouda, e.g.", answer: "cheesewheel" },
  55: { text: "Climbing vine", answer: "ivy" },
  56: { text: "Weeding tool", answer: "hoe" },
  57: { text: "Wildly bright, as a color", answer: "neon" },
  58: { text: '*"Ice Cream of the Future" since 1988', answer: "dippindots" },
  62: { text: "Something to make when tossing a coin into a fountain", answer: "wish" },
  65: { text: "Singer and AIDS charity founder ___ John", answer: "elton" },
  66: { text: "Genesis backdrop", answer: "eden" },
  67: { text: "With 41-Down, Buffalo's body of water", answer: "lake" },
  68: { text: "Corporate shake-up, for short", answer: "reorg" },
  69: { text: "Sales pitch display, informally", answer: "demo" },
  70: { text: "Slender", answer: "slim" },
};

export const down = {
  1: { text: "Twice-chewed food", answer: "cud" },
  2: { text: "Sports org. for Bill Russell", answer: "nba" },
  3: { text: "Backstabber's forte", answer: "betrayal" },
  4: { text: "Former late-night host Ferguson", answer: "craig" },
  5: { text: "Shiny bicycle attachment", answer: "relector" },
  6: { text: "Broadcast", answer: "air" },
  7: { text: "Sold-out theater inits.", answer: "sro" },
  8: { text: "Illinois city that's a symbol of Middle America", answer: "peoria" },
  9: { text: "Signed up", answer: "enlisted" },
  10: { text: "Bert and Ernie, for one", answer: "duo" },
  11: { text: '"Quit being so immature!"', answer: "growup" },
  12: { text: "Shoot for the stars", answer: "aspire" },
  13: { text: "Sticky secretion", answer: "resin" },
  19: { text: "Excessively", answer: "too" },
  21: { text: "Sounds during a dental exam", answer: "ahs" },
  24: { text: "Exhibit", answer: "show" },
  25: { text: "Drained of color", answer: "pale" },
  26: { text: "Drive-___ window", answer: "thru" },
  27: { text: "Alternative to a Ho Ho", answer: "twinkie" },
  32: { text: '"___ will always love you" (Whitney Houston lyric)', answer: "andi" },
  34: { text: "Target of a medicated dog collar", answer: "flea" },
  36: { text: '"Goodness me, absolutely not!"', answer: "heavensno" },
  38: { text: "Major Texas industry", answer: "ranching" },
  39: { text: "Goes pffft", answer: "dies" },
  40: { text: "Refusing to accept reality", answer: "in denail" },
  41: { text: "See 67-Across", answer: "erie" },
  42: { text: "Color akin to turquoise", answer: "teal" },
  46: { text: "___ Row (London street known for its tailors)", answer: "savile" },
  47: { text: "Modern lead-in to currency", answer: "crypto" },
  48: { text: "Like some watermelons or brackets", answer: "seeded" },
  49: { text: "Subject of many baa-a-ad puns?", answer: "ewe" },
  51: { text: "Orchard beverage", answer: "cider" },
  53: { text: "Babe", answer: "hon" },
  54: { text: "Roars with laughter", answer: "howls" },
  59: { text: '___ favor (Spanish "please")', answer: "por" },
  60: { text: "Praiseful poem", answer: "ode" },
  61: { text: "President pro ___", answer: "tem" },
  63: { text: "Bit of Winter Olympics equipment", answer: "ski" },
  64: { text: "Folded edge", answer: "hem" },
};

export const cells = [
  { letter: "c", across: 1, down: 1 },
  { letter: "n", across: 1, down: 2 },
  { letter: "b", across: 1, down: 3 },
  { letter: "c", across: 1, down: 4 },
  { letter: null, across: null, down: null },
  { letter: "r", across: 5, down: 5 },
  { letter: "a", across: 5, down: 6 },
  { letter: "s", across: 5, down: 7 },
  { letter: "p", across: 5, down: 8 },
  { letter: null, across: null, down: null },
  { letter: "e", across: 9, down: 9 },
  { letter: "d", across: 9, down: 10 },
  { letter: "g", across: 9, down: 11 },
  { letter: "a", across: 9, down: 12 },
  { letter: "r", across: 9, down: 13 },
  { letter: "u", across: 14, down: 1 },
  { letter: "b", across: 14, down: 2 },
  { letter: "e", across: 14, down: 3 },
  { letter: "r", across: 14, down: 4 },
  { letter: null, across: null, down: null },
  { letter: "e", across: 15, down: 5 },
  { letter: "i", across: 15, down: 6 },
  { letter: "r", across: 15, down: 7 },
  { letter: "e", across: 15, down: 8 },
  { letter: null, across: null, down: null },
  { letter: "n", across: 16, down: 9 },
  { letter: "u", across: 16, down: 10 },
  { letter: "r", across: 16, down: 11 },
  { letter: "s", across: 16, down: 12 },
  { letter: "e", across: 16, down: 13 },
  { letter: "d", across: 17, down: 1 },
  { letter: "a", across: 17, down: 2 },
  { letter: "t", across: 17, down: 3 },
  { letter: "a", across: 17, down: 4 },
  { letter: null, across: null, down: null },
  { letter: "f", across: 18, down: 5 },
  { letter: "r", across: 18, down: 6 },
  { letter: "o", across: 18, down: 7 },
  { letter: "o", across: 18, down: 8 },
  { letter: "t", across: 18, down: 19 },
  { letter: "l", across: 18, down: 9 },
  { letter: "o", across: 18, down: 10 },
  { letter: "o", across: 18, down: 11 },
  { letter: "p", across: 18, down: 12 },
  { letter: "s", across: 18, down: 13 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "r", across: 20, down: 3 },
  { letter: "i", across: 20, down: 4 },
  { letter: "a", across: 20, down: 21 },
  { letter: "l", across: 20, down: 5 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "r", across: 22, down: 8 },
  { letter: "o", across: 22, down: 19 },
  { letter: "i", across: 22, down: 9 },
  { letter: null, across: null, down: null },
  { letter: "w", across: 23, down: 11 },
  { letter: "i", across: 23, down: 12 },
  { letter: "i", across: 23, down: 13 },
  { letter: "s", across: 24, down: 24 },
  { letter: "p", across: 24, down: 25 },
  { letter: "a", across: 24, down: 3 },
  { letter: "g", across: 24, down: 4 },
  { letter: "h", across: 24, down: 21 },
  { letter: "e", across: 24, down: 5 },
  { letter: "t", across: 24, down: 26 },
  { letter: "t", across: 24, down: 27 },
  { letter: "i", across: 24, down: 8 },
  { letter: "o", across: 24, down: 19 },
  { letter: "s", across: 24, down: 9 },
  { letter: null, across: null, down: null },
  { letter: "u", across: 28, down: 11 },
  { letter: "r", across: 28, down: 12 },
  { letter: "n", across: 28, down: 13 },
  { letter: "h", across: 29, down: 24 },
  { letter: "a", across: 29, down: 25 },
  { letter: "y", across: 29, down: 3 },
  { letter: null, across: null, down: null },
  { letter: "s", across: 30, down: 21 },
  { letter: "c", across: 30, down: 5 },
  { letter: "h", across: 30, down: 26 },
  { letter: "w", across: 30, down: 27 },
  { letter: "a", across: 30, down: 8 },
  { letter: null, across: null, down: null },
  { letter: "t", across: 31, down: 9 },
  { letter: "a", across: 31, down: 32 },
  { letter: "p", across: 31, down: 11 },
  { letter: "e", across: 31, down: 12 },
  { letter: null, across: null, down: null },
  { letter: "o", across: 33, down: 24 },
  { letter: "l", across: 33, down: 25 },
  { letter: "a", across: 33, down: 3 },
  { letter: "f", across: 33, down: 34 },
  { letter: null, across: null, down: null },
  { letter: "t", across: 35, down: 5 },
  { letter: "r", across: 35, down: 26 },
  { letter: "i", across: 35, down: 27 },
  { letter: null, across: null, down: null },
  { letter: "h", across: 36, down: 36 },
  { letter: "e", across: 36, down: 9 },
  { letter: "n", across: 36, down: 32 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "w", across: 37, down: 24 },
  { letter: "e", across: 37, down: 25 },
  { letter: "l", across: 37, down: 3 },
  { letter: "l", across: 37, down: 34 },
  { letter: "r", across: 37, down: 38 },
  { letter: "o", across: 37, down: 5 },
  { letter: "u", across: 37, down: 26 },
  { letter: "n", across: 37, down: 27 },
  { letter: "d", across: 37, down: 39 },
  { letter: "e", across: 37, down: 36 },
  { letter: "d", across: 37, down: 9 },
  { letter: "d", across: 37, down: 32 },
  { letter: "i", across: 37, down: 40 },
  { letter: "e", across: 37, down: 41 },
  { letter: "t", across: 37, down: 42 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "e", across: 43, down: 34 },
  { letter: "a", across: 43, down: 38 },
  { letter: "r", across: 43, down: 5 },
  { letter: null, across: null, down: null },
  { letter: "k", across: 44, down: 27 },
  { letter: "i", across: 44, down: 39 },
  { letter: "a", across: 44, down: 36 },
  { letter: null, across: null, down: null },
  { letter: "i", across: 45, down: 32 },
  { letter: "n", across: 45, down: 40 },
  { letter: "r", across: 45, down: 41 },
  { letter: "e", across: 45, down: 42 },
  { letter: null, across: null, down: null },
  { letter: "s", across: 46, down: 46 },
  { letter: "c", across: 46, down: 47 },
  { letter: "a", across: 46, down: 34 },
  { letter: "n", across: 46, down: 38 },
  { letter: null, across: null, down: null },
  { letter: "s", across: 48, down: 48 },
  { letter: "i", across: 48, down: 27 },
  { letter: "e", across: 48, down: 39 },
  { letter: "v", across: 48, down: 36 },
  { letter: "e", across: 48, down: 49 },
  { letter: null, across: null, down: null },
  { letter: "d", across: 50, down: 40 },
  { letter: "i", across: 50, down: 41 },
  { letter: "a", across: 50, down: 42 },
  { letter: "c", across: 51, down: 51 },
  { letter: "a", across: 51, down: 46 },
  { letter: "r", across: 51, down: 47 },
  { letter: null, across: null, down: null },
  { letter: "c", across: 52, down: 38 },
  { letter: "h", across: 52, down: 53 },
  { letter: "e", across: 52, down: 48 },
  { letter: "e", across: 52, down: 27 },
  { letter: "s", across: 52, down: 39 },
  { letter: "e", across: 52, down: 36 },
  { letter: "w", across: 52, down: 49 },
  { letter: "h", across: 52, down: 54 },
  { letter: "e", across: 52, down: 40 },
  { letter: "e", across: 52, down: 41 },
  { letter: "l", across: 52, down: 42 },
  { letter: "i", across: 55, down: 51 },
  { letter: "v", across: 55, down: 46 },
  { letter: "y", across: 55, down: 47 },
  { letter: null, across: null, down: null },
  { letter: "h", across: 56, down: 38 },
  { letter: "o", across: 56, down: 53 },
  { letter: "e", across: 56, down: 48 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "n", across: 57, down: 36 },
  { letter: "e", across: 57, down: 49 },
  { letter: "o", across: 57, down: 54 },
  { letter: "n", across: 57, down: 40 },
  { letter: null, across: null, down: null },
  { letter: null, across: null, down: null },
  { letter: "d", across: 58, down: 51 },
  { letter: "i", across: 58, down: 46 },
  { letter: "p", across: 58, down: 47 },
  { letter: "p", across: 58, down: 59 },
  { letter: "i", across: 58, down: 38 },
  { letter: "n", across: 58, down: 53 },
  { letter: "d", across: 58, down: 48 },
  { letter: "o", across: 58, down: 60 },
  { letter: "t", across: 58, down: 61 },
  { letter: "s", across: 58, down: 36 },
  { letter: null, across: null, down: null },
  { letter: "w", across: 62, down: 54 },
  { letter: "i", across: 62, down: 40 },
  { letter: "s", across: 62, down: 63 },
  { letter: "h", across: 62, down: 64 },
  { letter: "e", across: 65, down: 51 },
  { letter: "l", across: 65, down: 46 },
  { letter: "t", across: 65, down: 47 },
  { letter: "o", across: 65, down: 59 },
  { letter: "n", across: 65, down: 38 },
  { letter: null, across: null, down: null },
  { letter: "e", across: 66, down: 48 },
  { letter: "d", across: 66, down: 60 },
  { letter: "e", across: 66, down: 61 },
  { letter: "n", across: 66, down: 36 },
  { letter: null, across: null, down: null },
  { letter: "l", across: 67, down: 54 },
  { letter: "a", across: 67, down: 40 },
  { letter: "k", across: 67, down: 63 },
  { letter: "e", across: 67, down: 64 },
  { letter: "r", across: 68, down: 51 },
  { letter: "e", across: 68, down: 46 },
  { letter: "o", across: 68, down: 47 },
  { letter: "r", across: 68, down: 59 },
  { letter: "g", across: 68, down: 38 },
  { letter: null, across: null, down: null },
  { letter: "d", across: 69, down: 48 },
  { letter: "e", across: 69, down: 60 },
  { letter: "m", across: 69, down: 61 },
  { letter: "o", across: 69, down: 36 },
  { letter: null, across: null, down: null },
  { letter: "s", across: 70, down: 54 },
  { letter: "l", across: 70, down: 40 },
  { letter: "i", across: 70, down: 63 },
  { letter: "m", across: 70, down: 64 },
];
